---
pg:
    host: myhost
    user: myuser
    db: mydb
    port: 0000
    osg_schema: osg
    sg_schema: sg


api:
    host: www.test.com
    port: 0000
    user: api_user
    passwd: api_pass

dirs:
    in: ./in