---
pg:
    host: myhost
    user: myuser
    db: mydb
    port: 0000
    osg_schema: osg
    sg_schema: sg
    tmp_schema: tmp
    read_user: myreaduser

ftp:
    host: www.test.com
    port: 0000
    user: api_user
    passwd: api_pass

directories:
    data_in: ./in